// lib/web-catalog/expanded-templates-catalog.ts
import { WebCatalogTemplate, TemplateCategory } from "./types";

export const EXPANDED_WEB_TEMPLATES: WebCatalogTemplate[] = [
  // ============================================
  // CATEGORÍA: BASIC (1 template)
  // Disponible para: Gratis, Catálogos, Básico IA, Profesional, Empresariales
  // ============================================

  {
    id: "basic-catalog-free",
    name: "Tienda Minimalista", // Nombre más atractivo
    description: "Diseño limpio y esencial, estilo boutique",
    longDescription:
      "Un diseño ultra-limpio que pone toda la atención en tus fotos. Sin distracciones, bordes suaves y tipografía clara. Ideal para empezar.",
    thumbnail: "https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?w=600&h=400&fit=crop",
    previewImages: [],
    layout: "modern-grid",
    style: "minimal",
    category: "basic",
    isPremium: false,
    bestFor: ["general", "moda", "artesania", "postres"],
    idealProductCount: { min: 1, max: 200 },
    features: [
      "Diseño ultra-limpio",
      "Carga instantánea",
      "Fácil navegación móvil",
      "Botones de acción claros",
      "Vista de producto enfocada",
    ],
    config: {
      columnsDesktop: 3,
      columnsMobile: 1, // 1 columna en móvil se ve más "App nativa"
      gap: "normal",
      cardStyle: "flat", // Cambio de 'outlined' a 'flat' para limpieza
      cardRadius: "xl", // Bordes mucho más redondeados
      imageRatio: "square",
      hoverEffect: "lift",
      clickAction: "modal",
      hasSearch: true,
      hasFilters: false,
      hasCart: false, // En básico quizás solo quieren ver
      hasFavorites: false,
      hasShareButtons: true,
      hasZoom: true,
      entranceAnimation: "fade",
      transitionSpeed: "normal",
      showLogo: true,
      showWatermark: true,
    },
    colorScheme: {
      primary: "#18181b", // Zinc-950 (Negro suave moderno)
      secondary: "#71717a", // Zinc-500
      accent: "#2563eb", // Azul vibrante para botones
      background: "#ffffff",
      cardBackground: "#ffffff",
      text: "#09090b",
      textMuted: "#71717a",
      border: "#f4f4f5", // Bordes casi invisibles
    },
    popularity: 100,
    tags: ["básico", "limpio", "moderno"],
  },

  // ============================================
  // CATEGORÍA: STANDARD (8 templates)
  // Disponible para: Básico IA, Profesional, Empresarial
  // ============================================

  {
    id: "modern-grid-clean",
    name: "Smart Grid Pro",
    description: "Estilo E-commerce moderno (Tipo Shopify)",
    longDescription:
      "El estándar de oro del comercio electrónico. Tarjetas con sombra suave, botones de compra visibles y filtros laterales. Inspira confianza.",
    thumbnail: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=600&h=400&fit=crop",
    previewImages: [],
    layout: "modern-grid",
    style: "modern",
    category: "standard",
    isPremium: false,
    bestFor: ["tecnologia", "moda", "calzado", "accesorios"],
    idealProductCount: { min: 12, max: 100 },
    features: [
      "Tarjetas con elevación suave",
      "Botón de compra rápido",
      "Filtros de categoría",
      "Buscador predictivo",
      "Layout espacioso",
    ],
    config: {
      columnsDesktop: 3,
      columnsMobile: 2,
      gap: "loose", // Más espacio blanco
      cardStyle: "elevated", // Sombra suave
      cardRadius: "lg",
      imageRatio: "square",
      hoverEffect: "lift",
      clickAction: "modal",
      hasSearch: true,
      hasFilters: true,
      hasCart: true,
      hasFavorites: true,
      hasShareButtons: true,
      hasZoom: true,
      entranceAnimation: "fade",
      transitionSpeed: "normal",
      showLogo: true,
      showWatermark: false,
    },
    colorScheme: {
      primary: "#3b82f6", // Azul moderno
      secondary: "#64748b",
      accent: "#f59e0b", // Ámbar para ofertas
      background: "#f8fafc", // Fondo gris muy tenue
      cardBackground: "#ffffff",
      text: "#0f172a",
      textMuted: "#64748b",
      border: "#e2e8f0",
    },
    popularity: 95,
    tags: ["shopify-style", "ventas", "profesional"],
  },

  {
    id: "masonry-fashion-elegant",
    name: "Galería Editorial", // Nombre más atractivo
    description: "Estilo Pinterest/Instagram para marcas visuales",
    longDescription:
      "Diseño asimétrico tipo Masonry que se adapta a tus fotos verticales y horizontales. Ideal para contar historias visuales.",
    thumbnail: "https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?w=600&h=400&fit=crop",
    previewImages: [],
    layout: "masonry",
    style: "elegant",
    category: "standard",
    isPremium: false,
    bestFor: ["moda", "arte", "decoracion", "eventos"],
    idealProductCount: { min: 6, max: 40 },
    features: [
      "Layout dinámico tipo Pinterest",
      "Imágenes completas sin recorte",
      "Tipografía elegante",
      "Fondo limpio",
      "Animación de entrada en cascada",
    ],
    config: {
      columnsDesktop: 3,
      columnsMobile: 2,
      gap: "normal",
      cardStyle: "flat", // Sin bordes para que parezca galería
      cardRadius: "2xl", // Muy redondeado
      imageRatio: "auto", // Respeta el tamaño original
      hoverEffect: "zoom",
      clickAction: "modal",
      hasSearch: true,
      hasFilters: true,
      hasCart: true,
      hasFavorites: true,
      hasShareButtons: true,
      hasZoom: true,
      entranceAnimation: "stagger", // Efecto cascada
      transitionSpeed: "slow",
      showLogo: true,
      showWatermark: false,
    },
    colorScheme: {
      primary: "#1c1917", // Stone-900
      secondary: "#57534e",
      accent: "#d97706",
      background: "#ffffff",
      cardBackground: "transparent", // Transparente para efecto galería
      text: "#1c1917",
      textMuted: "#78716c",
      border: "transparent",
    },
    popularity: 88,
    tags: ["pinterest", "moda", "galería"],
  },

  // ... (Puedes mantener los otros standard, pero actualizando sus configs así)
  // Voy a actualizar uno más que es muy popular: el de "Ofertas/Colorido"

  {
    id: "grid-colorful",
    name: "Pop & Play", // Nombre tipo Canva
    description: "Diseño vibrante y redondeado, ideal para destacar",
    longDescription:
      "Tarjetas con bordes muy redondeados, sombras suaves y colores de fondo sutiles. Perfecto para juguetes, regalos, postres o marcas juveniles.",
    thumbnail: "https://images.unsplash.com/photo-1472851294608-062f824d29cc?w=600&h=400&fit=crop",
    previewImages: [],
    layout: "modern-grid",
    style: "playful",
    category: "standard",
    isPremium: false,
    bestFor: ["niños", "regalos", "postres", "mascotas"],
    idealProductCount: { min: 12, max: 100 },
    features: [
      'Tarjetas "burbuja" (muy redondas)',
      "Sombras de color suaves",
      "Botones grandes y amigables",
      "Fuentes redondeadas",
      "Etiquetas de colores",
    ],
    config: {
      columnsDesktop: 3,
      columnsMobile: 2,
      gap: "loose",
      cardStyle: "soft", // Estilo suave
      cardRadius: "full", // O '3xl' para efecto burbuja
      imageRatio: "square",
      hoverEffect: "bounce", // Efecto rebote divertido
      clickAction: "modal",
      hasSearch: true,
      hasFilters: true,
      hasCart: true,
      hasFavorites: true,
      hasShareButtons: true,
      hasZoom: true,
      entranceAnimation: "slide",
      transitionSpeed: "normal",
      showLogo: true,
      showWatermark: false,
    },
    colorScheme: {
      primary: "#8b5cf6", // Violeta
      secondary: "#a78bfa",
      accent: "#f472b6", // Rosa
      background: "#fdf4ff", // Fondo rosa muy pálido
      cardBackground: "#ffffff",
      text: "#4c1d95",
      textMuted: "#6d28d9",
      border: "#f5d0fe",
    },
    popularity: 84,
    tags: ["divertido", "canva-style", "colorido"],
  },

  // Los demás standard se pueden quedar similares o actualizarlos con esta filosofía...
  // Pasemos a los Premium/Seasonal que deben verse INCREÍBLES

  // ============================================
  // CATEGORÍA: SEASONAL (7 templates)
  // Disponible SOLO para: Profesional, Empresarial
  // ============================================

  {
    id: "masonry-fashion-dark-premium",
    name: "Midnight Luxury",
    description: "Experiencia oscura inmersiva de alta gama",
    longDescription:
      "Diseño oscuro profundo con detalles en vidrio (glassmorphism). Ideal para joyería, relojes o moda nocturna. Transmite exclusividad.",
    thumbnail: "https://images.unsplash.com/photo-1483985988355-763728e1935b?w=600&h=400&fit=crop",
    previewImages: [],
    layout: "masonry",
    style: "luxury",
    category: "seasonal",
    isPremium: true,
    bestFor: ["joyeria", "relojes", "vip", "gala"],
    idealProductCount: { min: 6, max: 40 },
    features: [
      "Modo oscuro real (True Black)",
      "Efectos de cristal (Glassmorphism)",
      "Tipografía Serif elegante",
      "Detalles dorados sutiles",
      "Animaciones premium",
    ],
    proFeatures: ["Sin marca de agua", "Animaciones suaves", "Galería inmersiva", "Soporte video"],
    config: {
      columnsDesktop: 3,
      columnsMobile: 1,
      gap: "loose",
      cardStyle: "glass", // Efecto vidrio
      cardRadius: "xl",
      imageRatio: "auto",
      hoverEffect: "glow", // Brillo al pasar el mouse
      clickAction: "modal",
      hasSearch: true,
      hasFilters: true,
      hasCart: true,
      hasFavorites: true,
      hasShareButtons: true,
      hasZoom: true,
      entranceAnimation: "fade",
      transitionSpeed: "slow",
      showLogo: true,
      showWatermark: false,
    },
    colorScheme: {
      primary: "#fbbf24", // Dorado
      secondary: "#9ca3af", // Gris plata
      accent: "#f59e0b",
      background: "#09090b", // Casi negro
      cardBackground: "rgba(255, 255, 255, 0.03)", // Vidrio oscuro
      text: "#f8fafc",
      textMuted: "#94a3b8",
      border: "rgba(251, 191, 36, 0.1)", // Borde dorado sutil
      gradient: {
        from: "#18181b",
        to: "#09090b",
        direction: "to-b",
      },
    },
    popularity: 98,
    isNew: true,
    tags: ["lujo", "oscuro", "premium", "joyería"],
  },

  {
    id: "bento-modern-pro",
    name: "Bento UI Pro",
    description: "Diseño estructurado estilo Apple/Bento",
    longDescription:
      "Cuadrícula moderna y estructurada con bloques de información. Perfecto para tecnología, gadgets o catálogos muy organizados.",
    thumbnail: "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?w=600&h=400&fit=crop",
    previewImages: [],
    layout: "modern-grid",
    style: "modern",
    category: "seasonal",
    isPremium: true,
    bestFor: ["tecnologia", "oficina", "arquitectura"],
    idealProductCount: { min: 8, max: 32 },
    features: [
      "Layout Bento (cajas redondeadas)",
      "Espaciado perfecto",
      "Tipografía San Francisco/Inter",
      "Iconos minimalistas",
      "Fondos gris suave",
    ],
    proFeatures: ["Layout inteligente", "Sin marca de agua", "Micro-interacciones", "Filtros tipo App"],
    config: {
      columnsDesktop: 4,
      columnsMobile: 2,
      gap: "normal",
      cardStyle: "flat",
      cardRadius: "2xl", // Muy redondeado (estilo iOS)
      imageRatio: "square",
      hoverEffect: "scale",
      clickAction: "modal",
      hasSearch: true,
      hasFilters: true,
      hasCart: true,
      hasFavorites: true,
      hasShareButtons: true,
      hasZoom: true,
      entranceAnimation: "scale",
      transitionSpeed: "fast",
      showLogo: true,
      showWatermark: false,
    },
    colorScheme: {
      primary: "#000000",
      secondary: "#525252",
      accent: "#3b82f6", // Azul Apple
      background: "#f5f5f7", // Gris Apple
      cardBackground: "#ffffff",
      text: "#1d1d1f",
      textMuted: "#86868b",
      border: "transparent",
    },
    popularity: 92,
    isNew: true,
    tags: ["bento", "apple-style", "tech", "limpio"],
  },

  // (Mantén los demás templates seasonal que tenías, o actualízalos siguiendo este patrón de Radius XL y Gap Loose)
  {
    id: "sidebar-detail-warm",
    name: "Sidebar Detail Cálido",
    description: "Vista de lista lateral con detalle grande",
    longDescription:
      "Layout con sidebar de productos y vista detallada principal. Colores cálidos ideales para muebles, hogar y decoración.",
    thumbnail: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&h=400&fit=crop",
    previewImages: [],
    layout: "magazine",
    style: "modern",
    category: "standard",
    isPremium: false,
    bestFor: ["muebles", "decoracion", "electronica"],
    idealProductCount: { min: 8, max: 50 },
    features: [
      "Sidebar con grid de productos",
      "Vista detallada amplia",
      "Navegación intuitiva",
      "Rating de productos",
      "Botón de agregar directo",
    ],
    config: {
      columnsDesktop: 4,
      columnsMobile: 2,
      gap: "normal",
      cardStyle: "elevated",
      cardRadius: "xl",
      imageRatio: "square",
      hoverEffect: "lift",
      clickAction: "sidebar",
      hasSearch: true,
      hasFilters: true,
      hasCart: true,
      hasFavorites: true,
      hasShareButtons: true,
      hasZoom: true,
      entranceAnimation: "slide",
      transitionSpeed: "normal",
      showLogo: true,
      showWatermark: false,
    },
    colorScheme: {
      primary: "#ea580c",
      secondary: "#f97316",
      accent: "#fb923c",
      background: "#fff7ed",
      cardBackground: "#ffffff",
      text: "#1c1917",
      textMuted: "#78716c",
      border: "#fed7aa",
    },
    popularity: 86,
    tags: ["sidebar", "warm", "detail"],
  },
  {
    id: "sidebar-detail-blue",
    name: "Sidebar Detail Profesional",
    description: "Sidebar con tonos azules, perfecto para tech",
    longDescription:
      "Mismo layout de sidebar pero con paleta azul profesional. Ideal para electrónica y productos tecnológicos.",
    thumbnail: "https://images.unsplash.com/photo-1498049794561-7780e7231661?w=600&h=400&fit=crop",
    previewImages: [],
    layout: "magazine",
    style: "modern",
    category: "standard",
    isPremium: false,
    bestFor: ["electronica", "ferreteria", "general"],
    idealProductCount: { min: 8, max: 50 },
    features: [
      "Layout sidebar profesional",
      "Paleta azul corporativa",
      "Especificaciones técnicas",
      "Comparador de productos",
      "Filtros avanzados",
    ],
    config: {
      columnsDesktop: 4,
      columnsMobile: 2,
      gap: "normal",
      cardStyle: "outlined",
      cardRadius: "lg",
      imageRatio: "square",
      hoverEffect: "lift",
      clickAction: "sidebar",
      hasSearch: true,
      hasFilters: true,
      hasCart: true,
      hasFavorites: true,
      hasShareButtons: true,
      hasZoom: true,
      entranceAnimation: "fade",
      transitionSpeed: "fast",
      showLogo: true,
      showWatermark: false,
    },
    colorScheme: {
      primary: "#0284c7",
      secondary: "#0ea5e9",
      accent: "#06b6d4",
      background: "#f0f9ff",
      cardBackground: "#ffffff",
      text: "#0c4a6e",
      textMuted: "#64748b",
      border: "#bae6fd",
    },
    popularity: 82,
    tags: ["tech", "blue", "profesional"],
  },
  {
    id: "instagram-feed",
    name: "Instagram Feed",
    description: "Grid cuadrado estilo feed de Instagram",
    longDescription:
      "Grid perfecto de imágenes cuadradas como Instagram. Limpio, moderno y familiar para todos los usuarios.",
    thumbnail: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=600&h=400&fit=crop",
    previewImages: [],
    layout: "modern-grid",
    style: "modern",
    category: "standard",
    isPremium: false,
    bestFor: ["moda", "cosmeticos", "floreria"],
    idealProductCount: { min: 9, max: 60 },
    features: [
      "Grid cuadrado perfecto",
      "Estilo Instagram familiar",
      "Modal con detalles",
      "Likes y favoritos",
      "Compartir directo",
    ],
    config: {
      columnsDesktop: 2,
      columnsMobile: 2,
      gap: "tight",
      cardStyle: "flat",
      cardRadius: "none",
      imageRatio: "square",
      hoverEffect: "zoom",
      clickAction: "modal",
      hasSearch: true,
      hasFilters: false,
      hasCart: true,
      hasFavorites: true,
      hasShareButtons: true,
      hasZoom: true,
      entranceAnimation: "fade",
      transitionSpeed: "fast",
      showLogo: true,
      showWatermark: false,
    },
    colorScheme: {
      primary: "#db2777",
      secondary: "#ec4899",
      accent: "#f472b6",
      background: "#fdf2f8",
      cardBackground: "#ffffff",
      text: "#1f2937",
      textMuted: "#6b7280",
      border: "#fbcfe8",
      gradient: {
        from: "#ec4899",
        to: "#f472b6",
        direction: "to-r",
      },
    },
    popularity: 93,
    tags: ["instagram", "social", "square"],
  },
  {
    id: "polaroid-vintage",
    name: "Polaroid Vintage",
    description: "Estilo polaroid vintage con fotos inclinadas",
    longDescription:
      "Cards estilo foto polaroid con rotaciones aleatorias. Nostálgico y único, perfecto para productos artesanales.",
    thumbnail: "https://images.unsplash.com/photo-1516476892398-f666b0e9d976?w=600&h=400&fit=crop",
    previewImages: [],
    layout: "masonry",
    style: "playful",
    category: "standard",
    isPremium: false,
    bestFor: ["decoracion", "floreria", "alimentos"],
    idealProductCount: { min: 6, max: 36 },
    features: [
      "Estilo polaroid único",
      "Rotaciones aleatorias",
      "Sombras realistas",
      "Textura vintage",
      "Hover interactivo",
    ],
    config: {
      columnsDesktop: 3,
      columnsMobile: 1,
      gap: "loose",
      cardStyle: "elevated",
      cardRadius: "sm",
      imageRatio: "square",
      hoverEffect: "tilt",
      clickAction: "modal",
      hasSearch: true,
      hasFilters: true,
      hasCart: true,
      hasFavorites: true,
      hasShareButtons: true,
      hasZoom: true,
      entranceAnimation: "scale",
      transitionSpeed: "normal",
      showLogo: true,
      showWatermark: false,
    },
    colorScheme: {
      primary: "#78716c",
      secondary: "#a8a29e",
      accent: "#d6d3d1",
      background: "#fafaf9",
      cardBackground: "#ffffff",
      text: "#1c1917",
      textMuted: "#57534e",
      border: "#e7e5e4",
    },
    popularity: 73,
    tags: ["vintage", "polaroid", "creative"],
  },
  {
    id: "carousel-dynamic",
    name: "Carousel Dinámico",
    description: "Slider interactivo con múltiples vistas",
    longDescription:
      "Carousel moderno con múltiples productos visibles. Perfecto para catálogos pequeños o promociones especiales.",
    thumbnail: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&h=400&fit=crop",
    previewImages: [],
    layout: "carousel",
    style: "playful",
    category: "standard",
    isPremium: false,
    bestFor: ["floreria", "alimentos", "decoracion"],
    idealProductCount: { min: 4, max: 24 },
    features: ["Auto-play opcional", "Touch swipe", "Dots navigation", "Lazy loading"],
    config: {
      columnsDesktop: 3,
      columnsMobile: 1,
      gap: "normal",
      cardStyle: "elevated",
      cardRadius: "xl",
      imageRatio: "square",
      hoverEffect: "lift",
      clickAction: "modal",
      hasSearch: false,
      hasFilters: false,
      hasCart: true,
      hasFavorites: false,
      hasShareButtons: true,
      hasZoom: true,
      entranceAnimation: "fade",
      transitionSpeed: "normal",
      showLogo: true,
      showWatermark: false,
    },
    colorScheme: {
      primary: "#dc2626",
      secondary: "#ef4444",
      accent: "#f87171",
      background: "#fef2f2",
      cardBackground: "#ffffff",
      text: "#1f2937",
      textMuted: "#6b7280",
      border: "#fecaca",
      gradient: {
        from: "#fee2e2",
        to: "#fecaca",
        direction: "to-br",
      },
    },
    popularity: 72,
    tags: ["divertido", "colorido", "dinámico"],
  },
  {
    id: "sidebar-detail-luxury",
    name: "Sidebar Luxury Premium",
    description: "Versión premium con tema oscuro elegante y detalles dorados",
    longDescription:
      "Layout sidebar con tema oscuro y detalles dorados. Sin marca de agua. Para catálogos de lujo y alta gama.",
    thumbnail: "https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=600&h=400&fit=crop",
    previewImages: [],
    layout: "magazine",
    style: "luxury",
    category: "seasonal",
    isPremium: true,
    bestFor: ["joyeria", "muebles", "decoracion"],
    idealProductCount: { min: 8, max: 50 },
    features: ["Tema oscuro elegante", "Detalles dorados", "Vista 360° productos", "Zoom ultra HD"],
    proFeatures: ["Sin marca de agua", "Galería 360° exclusiva", "Video preview", "Colores personalizables"],
    config: {
      columnsDesktop: 4,
      columnsMobile: 2,
      gap: "normal",
      cardStyle: "glass",
      cardRadius: "xl",
      imageRatio: "square",
      hoverEffect: "glow",
      clickAction: "sidebar",
      hasSearch: true,
      hasFilters: true,
      hasCart: true,
      hasFavorites: true,
      hasShareButtons: true,
      hasZoom: true,
      entranceAnimation: "scale",
      transitionSpeed: "slow",
      showLogo: true,
      showWatermark: false,
    },
    colorScheme: {
      primary: "#fbbf24",
      secondary: "#f59e0b",
      accent: "#fde047",
      background: "#0f172a",
      cardBackground: "rgba(251, 191, 36, 0.05)",
      text: "#f8fafc",
      textMuted: "#94a3b8",
      border: "rgba(251, 191, 36, 0.2)",
      gradient: {
        from: "#1e293b",
        to: "#0f172a",
        direction: "to-b",
      },
    },
    popularity: 79,
    isNew: true,
    tags: ["premium", "luxury", "gold", "seasonal"],
  },
  {
    id: "grid-compact-pro",
    name: "Grid Compacto Pro",
    description: "Grid denso para mostrar muchos productos",
    longDescription:
      "Grid de 4-5 columnas muy compacto. Ideal para catálogos con 50+ productos. Vista de lista opcional.",
    thumbnail: "https://images.unsplash.com/photo-1445205170230-053b83016050?w=600&h=400&fit=crop",
    previewImages: [],
    layout: "modern-grid",
    style: "minimal",
    category: "seasonal",
    isPremium: true,
    bestFor: ["ferreteria", "electronica", "general"],
    idealProductCount: { min: 50, max: 500 },
    features: ["Grid de 5 columnas", "Vista muy compacta", "Toggle list/grid", "Filtros avanzados"],
    proFeatures: ["Hasta 500 productos", "Sin marca de agua", "Exportar lista", "Comparador múltiple"],
    config: {
      columnsDesktop: 5,
      columnsMobile: 2,
      gap: "tight",
      cardStyle: "outlined",
      cardRadius: "sm",
      imageRatio: "square",
      hoverEffect: "lift",
      clickAction: "expand",
      hasSearch: true,
      hasFilters: true,
      hasCart: true,
      hasFavorites: true,
      hasShareButtons: false,
      hasZoom: true,
      entranceAnimation: "none",
      transitionSpeed: "fast",
      showLogo: true,
      showWatermark: false,
    },
    colorScheme: {
      primary: "#3b82f6",
      secondary: "#60a5fa",
      accent: "#93c5fd",
      background: "#f8fafc",
      cardBackground: "#ffffff",
      text: "#0f172a",
      textMuted: "#64748b",
      border: "#e2e8f0",
    },
    popularity: 76,
    tags: ["compact", "dense", "professional", "seasonal"],
  },
  {
    id: "magazine-editorial-pro",
    name: "Magazine Editorial Premium",
    description: "Estilo revista de moda con tipografía grande",
    longDescription:
      "Layout asimétrico inspirado en revistas Vogue/Harper's. Tipografía impactante, imágenes full-bleed.",
    thumbnail: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=600&h=400&fit=crop",
    previewImages: [],
    layout: "magazine",
    style: "bold",
    category: "seasonal",
    isPremium: true,
    bestFor: ["moda", "joyeria", "cosmeticos"],
    idealProductCount: { min: 6, max: 30 },
    features: ["Layout editorial asimétrico", "Tipografía display grande", "Imágenes full-bleed", "Parallax scrolling"],
    proFeatures: ["Fuentes custom premium", "Sin marca de agua", "Video headers", "Animaciones parallax"],
    config: {
      columnsDesktop: 3,
      columnsMobile: 1,
      gap: "loose",
      cardStyle: "flat",
      cardRadius: "none",
      imageRatio: "portrait",
      hoverEffect: "zoom",
      clickAction: "modal",
      hasSearch: false,
      hasFilters: false,
      hasCart: true,
      hasFavorites: true,
      hasShareButtons: true,
      hasZoom: true,
      entranceAnimation: "slide",
      transitionSpeed: "slow",
      showLogo: true,
      showWatermark: false,
      customFonts: ["Playfair Display", "Montserrat"],
    },
    colorScheme: {
      primary: "#0f172a",
      secondary: "#dc2626",
      accent: "#fbbf24",
      background: "#ffffff",
      cardBackground: "#f8fafc",
      text: "#0f172a",
      textMuted: "#64748b",
      border: "#e2e8f0",
    },
    popularity: 81,
    isNew: true,
    tags: ["editorial", "magazine", "bold", "seasonal"],
  },
  {
    id: "netflix-carousel-pro",
    name: "Netflix Carousel Premium",
    description: "Carousels horizontales por categoría estilo Netflix",
    longDescription:
      "Múltiples carousels horizontales organizados por categoría. Navegación fluida con scroll horizontal.",
    thumbnail: "https://images.unsplash.com/photo-1522869635100-9f4c5e86aa37?w=600&h=400&fit=crop",
    previewImages: [],
    layout: "horizontal-scroll",
    style: "modern",
    category: "seasonal",
    isPremium: true,
    bestFor: ["electronica", "moda", "general"],
    idealProductCount: { min: 20, max: 100 },
    features: [
      "Carousels por categoría",
      "Scroll horizontal fluido",
      "Lazy loading inteligente",
      "Navegación por flechas",
    ],
    proFeatures: ["Hasta 100 productos", "Sin marca de agua", "Autoplay configurable", "Touch gestures premium"],
    config: {
      columnsDesktop: 5,
      columnsMobile: 2,
      gap: "normal",
      cardStyle: "elevated",
      cardRadius: "md",
      imageRatio: "landscape",
      hoverEffect: "zoom",
      clickAction: "modal",
      hasSearch: true,
      hasFilters: true,
      hasCart: true,
      hasFavorites: true,
      hasShareButtons: true,
      hasZoom: true,
      entranceAnimation: "slide",
      transitionSpeed: "fast",
      showLogo: true,
      showWatermark: false,
    },
    colorScheme: {
      primary: "#dc2626",
      secondary: "#991b1b",
      accent: "#fbbf24",
      background: "#0f172a",
      cardBackground: "#1e293b",
      text: "#f8fafc",
      textMuted: "#94a3b8",
      border: "#334155",
    },
    popularity: 89,
    isNew: true,
    tags: ["carousel", "netflix", "horizontal", "seasonal"],
  },
  {
    id: "showcase-fullscreen-pro",
    name: "Showcase Fullscreen Premium",
    description: "Presentación fullscreen de alto impacto para productos exclusivos",
    longDescription:
      "Template premium con efecto de showcase fullscreen. Cada producto ocupa toda la pantalla con transiciones cinematográficas.",
    thumbnail: "https://images.unsplash.com/photo-1618005198920-f0cb6201c115?w=600&h=400&fit=crop",
    previewImages: [],
    layout: "showcase",
    style: "luxury",
    category: "seasonal",
    isPremium: true,
    bestFor: ["joyeria", "muebles", "decoracion"],
    idealProductCount: { min: 5, max: 20 },
    features: [
      "Presentación fullscreen",
      "Transiciones cinematográficas",
      "Galería inmersiva 360°",
      "Música de fondo (opcional)",
    ],
    proFeatures: ["Experiencia inmersiva exclusiva", "Sin marca de agua", "Video backgrounds", "Animaciones 3D"],
    config: {
      columnsDesktop: 2,
      columnsMobile: 2,
      gap: "normal",
      cardStyle: "flat",
      cardRadius: "none",
      imageRatio: "landscape",
      hoverEffect: "tilt",
      clickAction: "modal",
      hasSearch: false,
      hasFilters: false,
      hasCart: true,
      hasFavorites: true,
      hasShareButtons: true,
      hasZoom: true,
      entranceAnimation: "scale",
      transitionSpeed: "slow",
      showLogo: true,
      showWatermark: false,
    },
    colorScheme: {
      primary: "#0f172a",
      secondary: "#fbbf24",
      accent: "#f59e0b",
      background: "#000000",
      cardBackground: "#0f172a",
      text: "#f8fafc",
      textMuted: "#94a3b8",
      border: "#1e293b",
      gradient: {
        from: "#0f172a",
        to: "#000000",
        direction: "to-b",
      },
    },
    popularity: 75,
    isNew: true,
    tags: ["premium", "luxury", "exclusivo", "seasonal"],
  },
  // ============================================
  // NUEVOS: MINIMALISTAS & OUTLINED (Muebles/Moda)
  // ============================================

  {
    id: "architect-studio",
    name: "Estudio Arquitecto",
    description: "Líneas finas y estructura rígida",
    longDescription:
      "Inspirado en planos arquitectónicos. Bordes negros de 1px, sin sombras, fondo blanco puro. Perfecto para muebles, diseño y arte.",
    thumbnail: "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=600&h=400&fit=crop",
    previewImages: [],
    layout: "modern-grid",
    style: "minimal",
    category: "standard",
    isPremium: false,
    bestFor: ["muebles", "arquitectura", "arte"],
    idealProductCount: { min: 6, max: 50 },
    features: [
      "Estilo Wireframe",
      "Bordes negros definidos",
      "Sin distracciones visuales",
      "Tipografía Monospace (técnica)",
      "Máxima legibilidad",
    ],
    config: {
      columnsDesktop: 3,
      columnsMobile: 1,
      gap: "normal",
      cardStyle: "outlined", // Borde visible
      cardRadius: "none", // Cuadrado perfecto
      imageRatio: "square",
      hoverEffect: "none", // Sin movimiento, solo cambio de color borde
      clickAction: "modal",
      hasSearch: true,
      hasFilters: true,
      hasCart: true,
      hasFavorites: false,
      hasShareButtons: true,
      hasZoom: true,
      entranceAnimation: "none",
      transitionSpeed: "fast",
      showLogo: true,
      showWatermark: false,
    },
    colorScheme: {
      primary: "#000000",
      secondary: "#404040",
      accent: "#000000",
      background: "#ffffff",
      cardBackground: "#ffffff",
      text: "#000000",
      textMuted: "#525252",
      border: "#000000", // Borde negro sólido
    },
    popularity: 80,
    tags: ["wireframe", "muebles", "técnico"],
  },

  {
    id: "boutique-line-art",
    name: "Boutique Line Art",
    description: "Delicado y femenino con bordes suaves",
    longDescription:
      "Un toque de elegancia minimalista. Bordes muy finos en tonos taupe o gris cálido. Ideal para ropa de mujer, lencería o skincare.",
    thumbnail: "https://images.unsplash.com/photo-1445205170230-053b83016050?w=600&h=400&fit=crop",
    previewImages: [],
    layout: "masonry",
    style: "elegant",
    category: "standard",
    isPremium: false,
    bestFor: ["moda", "skincare", "lenceria"],
    idealProductCount: { min: 10, max: 60 },
    features: ["Bordes ultra-finos", "Paleta nude/taupe", "Layout aireado", "Tipografía Serif moderna"],
    config: {
      columnsDesktop: 4,
      columnsMobile: 2,
      gap: "loose",
      cardStyle: "outlined",
      cardRadius: "sm", // Ligero redondeo
      imageRatio: "portrait", // Mejor para ropa
      hoverEffect: "lift",
      clickAction: "modal",
      hasSearch: true,
      hasFilters: true,
      hasCart: true,
      hasFavorites: true,
      hasShareButtons: true,
      hasZoom: true,
      entranceAnimation: "fade",
      transitionSpeed: "slow",
      showLogo: true,
      showWatermark: false,
    },
    colorScheme: {
      primary: "#78716c", // Stone-500
      secondary: "#a8a29e",
      accent: "#d6d3d1",
      background: "#fafaf9", // Stone-50
      cardBackground: "#ffffff",
      text: "#44403c",
      textMuted: "#78716c",
      border: "#e7e5e4", // Borde muy sutil
    },
    popularity: 87,
    tags: ["boutique", "femenino", "suave"],
  },

  {
    id: "gallery-frame",
    name: "Galería de Arte",
    description: "Marco ancho tipo paspartú para resaltar fotos",
    longDescription:
      "Tus productos son obras de arte. Este diseño añade un marco blanco ancho alrededor de cada foto, creando un efecto de galería.",
    thumbnail: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=600&h=400&fit=crop",
    previewImages: [],
    layout: "modern-grid",
    style: "minimal",
    category: "standard",
    isPremium: true,
    bestFor: ["arte", "fotografia", "decoracion", "joyeria"],
    idealProductCount: { min: 1, max: 30 },
    features: [
      "Efecto paspartú (marco blanco)",
      "Sombra profunda al hover",
      "Fondo gris museo",
      "Texto minimalista abajo",
    ],
    config: {
      columnsDesktop: 3,
      columnsMobile: 1,
      gap: "loose",
      cardStyle: "flat", // Plano pero...
      cardRadius: "none",
      imageRatio: "square",
      hoverEffect: "glow", // ...con sombra al pasar
      clickAction: "modal",
      hasSearch: true,
      hasFilters: false,
      hasCart: true,
      hasFavorites: true,
      hasShareButtons: true,
      hasZoom: true,
      entranceAnimation: "scale",
      transitionSpeed: "normal",
      showLogo: true,
      showWatermark: false,
    },
    colorScheme: {
      primary: "#262626",
      secondary: "#525252",
      accent: "#000000",
      background: "#f5f5f5", // Gris museo
      cardBackground: "#ffffff", // Marco blanco
      text: "#171717",
      textMuted: "#737373",
      border: "transparent",
    },
    popularity: 78,
    tags: ["arte", "marco", "galería", "clean"],
  },
  // ============================================
  // NUEVOS: NAVIDAD & TEMPORADA
  // ============================================

  {
    id: "christmas-classic",
    name: "Navidad Clásica",
    description: "Diseño festivo rojo y verde para temporada",
    longDescription:
      "El espíritu navideño en tu catálogo. Bordes dorados, fondo rojo cálido y detalles festivos. Ideal para regalos y juguetes.",
    thumbnail: "https://images.unsplash.com/photo-1543589077-47d81606c1bf?w=600&h=400&fit=crop",
    previewImages: [],
    layout: "modern-grid",
    style: "playful",
    category: "seasonal",
    isPremium: false, // Disponible para todos en temporada
    bestFor: ["regalos", "juguetes", "postres"],
    idealProductCount: { min: 8, max: 50 },
    features: [
      "Paleta de colores navideña",
      "Detalles dorados en botones",
      "Cards muy redondeadas (Cozy)",
      "Fondo con textura sutil",
    ],
    config: {
      columnsDesktop: 3,
      columnsMobile: 2,
      gap: "loose",
      cardStyle: "elevated",
      cardRadius: "xl", // Muy redondo
      imageRatio: "square",
      hoverEffect: "bounce",
      clickAction: "modal",
      hasSearch: true,
      hasFilters: true,
      hasCart: true,
      hasFavorites: true,
      hasShareButtons: true,
      hasZoom: true,
      entranceAnimation: "slide",
      transitionSpeed: "normal",
      showLogo: true,
      showWatermark: false,
    },
    colorScheme: {
      primary: "#dc2626", // Rojo Navidad
      secondary: "#166534", // Verde Pino
      accent: "#f59e0b", // Dorado
      background: "#fef2f2", // Nieve rojiza
      cardBackground: "#ffffff",
      text: "#7f1d1d", // Texto rojo oscuro
      textMuted: "#991b1b",
      border: "#fca5a5",
    },
    popularity: 99,
    tags: ["navidad", "fiestas", "rojo", "regalos"],
  },

  {
    id: "winter-wonderland",
    name: "Invierno Mágico",
    description: "Estilo elegante azul hielo y plata",
    longDescription:
      "Un diseño invernal sofisticado. Tonos azules fríos, blancos y plateados. Perfecto para tecnología, joyería de plata o moda de invierno.",
    thumbnail: "https://images.unsplash.com/photo-1482331318722-b87273d42e4e?w=600&h=400&fit=crop",
    previewImages: [],
    layout: "masonry",
    style: "elegant",
    category: "seasonal",
    isPremium: true,
    bestFor: ["joyeria", "tecnologia", "moda"],
    idealProductCount: { min: 6, max: 40 },
    features: [
      'Estilo "Frozen" elegante',
      "Efecto cristal (Glassmorphism)",
      "Sombras azules suaves",
      "Tipografía fina",
    ],
    config: {
      columnsDesktop: 3,
      columnsMobile: 1,
      gap: "normal",
      cardStyle: "glass",
      cardRadius: "lg",
      imageRatio: "auto",
      hoverEffect: "glow",
      clickAction: "modal",
      hasSearch: true,
      hasFilters: true,
      hasCart: true,
      hasFavorites: true,
      hasShareButtons: true,
      hasZoom: true,
      entranceAnimation: "fade",
      transitionSpeed: "slow",
      showLogo: true,
      showWatermark: false,
    },
    colorScheme: {
      primary: "#0ea5e9", // Azul Hielo
      secondary: "#64748b", // Plata
      accent: "#38bdf8",
      background: "#f0f9ff", // Nieve azulada
      cardBackground: "rgba(255, 255, 255, 0.8)",
      text: "#0c4a6e",
      textMuted: "#64748b",
      border: "#bae6fd",
    },
    popularity: 88,
    tags: ["invierno", "azul", "elegante", "glass"],
  },

  {
    id: "new-year-gala",
    name: "Gala Año Nuevo",
    description: "Negro y Dorado para eventos exclusivos",
    longDescription:
      "El lujo de la fiesta de fin de año. Fondo oscuro, tipografía dorada y líneas finas. Para licores, vestidos de noche y eventos.",
    thumbnail: "https://images.unsplash.com/photo-1467810563316-b5476525c0f9?w=600&h=400&fit=crop",
    previewImages: [],
    layout: "showcase",
    style: "luxury",
    category: "seasonal",
    isPremium: true,
    bestFor: ["licores", "eventos", "moda"],
    idealProductCount: { min: 4, max: 20 },
    features: [
      "Contraste alto Negro/Dorado",
      "Bordes delgados dorados",
      "Tipografía Serif clásica",
      "Layout de showcase",
    ],
    config: {
      columnsDesktop: 2,
      columnsMobile: 1,
      gap: "loose",
      cardStyle: "outlined", // Borde dorado
      cardRadius: "none", // Cuadrado elegante
      imageRatio: "portrait",
      hoverEffect: "scale",
      clickAction: "modal",
      hasSearch: false,
      hasFilters: false,
      hasCart: true,
      hasFavorites: false,
      hasShareButtons: true,
      hasZoom: true,
      entranceAnimation: "slide",
      transitionSpeed: "slow",
      showLogo: true,
      showWatermark: false,
    },
    colorScheme: {
      primary: "#fbbf24", // Dorado
      secondary: "#d4d4d8",
      accent: "#f59e0b",
      background: "#000000",
      cardBackground: "#09090b",
      text: "#fef3c7", // Dorado pálido
      textMuted: "#a1a1aa",
      border: "#fbbf24", // Borde dorado
    },
    popularity: 85,
    tags: ["año nuevo", "fiesta", "negro", "lujo"],
  },
];
