import { WebCatalogTemplate } from "./types";

export const EXPANDED_WEB_TEMPLATES: WebCatalogTemplate[] = [
  // ============================================
  // CATEGORÍA: BASIC (1 template)
  // ============================================
  {
    id: "basic-catalog-free",
    name: "Tienda Minimalista",
    description: "Diseño limpio y esencial, estilo boutique",
    longDescription:
      "Un diseño ultra-limpio que pone toda la atención en tus fotos. Sin distracciones, bordes suaves y tipografía clara.",
    thumbnail: "https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?w=600&h=400&fit=crop",
    previewImages: [],
    layout: "modern-grid",
    style: "minimal",
    category: "basic",
    isPremium: false,
    bestFor: ["general", "moda", "artesania"],
    idealProductCount: { min: 1, max: 200 },
    features: ["Diseño ultra-limpio", "Carga instantánea"],
    config: {
      columnsDesktop: 3,
      columnsMobile: 1,
      gap: "normal",
      cardStyle: "flat",
      cardRadius: "md",
      imageRatio: "square",
      hoverEffect: "lift",
      clickAction: "modal",
      hasSearch: true,
      hasFilters: false,
      hasCart: false,
      hasFavorites: false,
      hasShareButtons: true,
      hasZoom: true,
      entranceAnimation: "fade",
      transitionSpeed: "normal",
      showLogo: true,
      showWatermark: true,
    },
    colorScheme: {
      primary: "#18181b", // Zinc-950 (Neutro)
      secondary: "#71717a",
      accent: "#2563eb",
      background: "#ffffff",
      cardBackground: "#ffffff",
      text: "#09090b",
      textMuted: "#71717a",
      border: "#f4f4f5",
    },
    popularity: 100,
    tags: ["básico", "limpio"],
  },

  // ============================================
  // CATEGORÍA: STANDARD (Variedad de Colores)
  // ============================================

  {
    id: "modern-grid-clean",
    name: "Tech Blue",
    description: "Estilo E-commerce clásico y confiable",
    longDescription:
      "El estándar de oro del comercio electrónico. Tarjetas con sombra suave y tonos azules corporativos.",
    thumbnail: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=600&h=400&fit=crop",
    previewImages: [],
    layout: "modern-grid",
    style: "modern",
    category: "standard",
    isPremium: false,
    bestFor: ["tecnologia", "servicios"],
    idealProductCount: { min: 12, max: 100 },
    features: ["Tarjetas con elevación", "Filtros de categoría"],
    config: {
      columnsDesktop: 3,
      columnsMobile: 2,
      gap: "loose",
      cardStyle: "elevated",
      cardRadius: "lg",
      imageRatio: "square",
      hoverEffect: "lift",
      clickAction: "modal",
      hasSearch: true,
      hasFilters: true,
      hasCart: true,
      hasFavorites: true,
      hasShareButtons: true,
      hasZoom: true,
      entranceAnimation: "fade",
      transitionSpeed: "normal",
      showLogo: true,
      showWatermark: false,
    },
    colorScheme: {
      primary: "#0284c7", // Sky-600 (Azul Vibrante)
      secondary: "#38bdf8",
      accent: "#f59e0b",
      background: "#f0f9ff",
      cardBackground: "#ffffff",
      text: "#0c4a6e",
      textMuted: "#64748b",
      border: "#e0f2fe",
    },
    popularity: 95,
    tags: ["azul", "tech", "ventas"],
  },

  {
    id: "masonry-fashion-elegant",
    name: "Nature Green",
    description: "Tonos orgánicos y frescos",
    longDescription:
      "Diseño asimétrico tipo Masonry con una paleta verde natural. Ideal para plantas, comida saludable o productos eco.",
    thumbnail: "https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?w=600&h=400&fit=crop",
    previewImages: [],
    layout: "masonry",
    style: "elegant",
    category: "standard",
    isPremium: false,
    bestFor: ["plantas", "comida", "organico"],
    idealProductCount: { min: 6, max: 40 },
    features: ["Layout dinámico", "Estilo orgánico"],
    config: {
      columnsDesktop: 3,
      columnsMobile: 2,
      gap: "normal",
      cardStyle: "flat",
      cardRadius: "xl",
      imageRatio: "auto",
      hoverEffect: "zoom",
      clickAction: "modal",
      hasSearch: true,
      hasFilters: true,
      hasCart: true,
      hasFavorites: true,
      hasShareButtons: true,
      hasZoom: true,
      entranceAnimation: "stagger",
      transitionSpeed: "slow",
      showLogo: true,
      showWatermark: false,
    },
    colorScheme: {
      primary: "#15803d", // Green-700 (Verde Hoja)
      secondary: "#86efac",
      accent: "#d97706",
      background: "#f0fdf4", // Menta suave
      cardBackground: "#ffffff",
      text: "#14532d",
      textMuted: "#166534",
      border: "#dcfce7",
    },
    popularity: 88,
    tags: ["verde", "natural", "galería"],
  },

  {
    id: "grid-colorful",
    name: "Berry Pop",
    description: "Vibrante, divertido y juvenil",
    longDescription:
      "Tarjetas muy redondeadas con sombras de color rosa y violeta. Perfecto para juguetes, regalos o marcas femeninas.",
    thumbnail: "https://images.unsplash.com/photo-1472851294608-062f824d29cc?w=600&h=400&fit=crop",
    previewImages: [],
    layout: "modern-grid",
    style: "playful",
    category: "standard",
    isPremium: false,
    bestFor: ["niños", "regalos", "postres"],
    idealProductCount: { min: 12, max: 100 },
    features: ["Cards burbuja", "Sombras de color"],
    config: {
      columnsDesktop: 3,
      columnsMobile: 2,
      gap: "loose",
      cardStyle: "soft",
      cardRadius: "3xl", // Muy redondo
      imageRatio: "square",
      hoverEffect: "bounce",
      clickAction: "modal",
      hasSearch: true,
      hasFilters: true,
      hasCart: true,
      hasFavorites: true,
      hasShareButtons: true,
      hasZoom: true,
      entranceAnimation: "slide",
      transitionSpeed: "normal",
      showLogo: true,
      showWatermark: false,
    },
    colorScheme: {
      primary: "#be185d", // Pink-700 (Frambuesa)
      secondary: "#f472b6",
      accent: "#8b5cf6", // Violeta
      background: "#fff1f2", // Rosa pálido
      cardBackground: "#ffffff",
      text: "#831843",
      textMuted: "#9d174d",
      border: "#fbcfe8",
    },
    popularity: 84,
    tags: ["rosa", "divertido", "pop"],
  },

  {
    id: "sidebar-detail-warm",
    name: "Sunset Orange",
    description: "Cálido y acogedor para hogar",
    longDescription:
      "Layout con sidebar y tonos terracota/naranja. Ideal para muebles, decoración, panaderías o cafeterías.",
    thumbnail: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&h=400&fit=crop",
    previewImages: [],
    layout: "magazine",
    style: "modern",
    category: "standard",
    isPremium: false,
    bestFor: ["hogar", "panaderia", "decoracion"],
    idealProductCount: { min: 8, max: 50 },
    features: ["Sidebar lateral", "Vista detallada"],
    config: {
      columnsDesktop: 4,
      columnsMobile: 2,
      gap: "normal",
      cardStyle: "elevated",
      cardRadius: "lg",
      imageRatio: "square",
      hoverEffect: "lift",
      clickAction: "sidebar",
      hasSearch: true,
      hasFilters: true,
      hasCart: true,
      hasFavorites: true,
      hasShareButtons: true,
      hasZoom: true,
      entranceAnimation: "slide",
      transitionSpeed: "normal",
      showLogo: true,
      showWatermark: false,
    },
    colorScheme: {
      primary: "#c2410c", // Orange-700 (Terracota)
      secondary: "#fdba74",
      accent: "#ea580c",
      background: "#fff7ed", // Naranja muy suave
      cardBackground: "#ffffff",
      text: "#431407",
      textMuted: "#9a3412",
      border: "#fed7aa",
    },
    popularity: 86,
    tags: ["naranja", "cálido", "hogar"],
  },

  {
    id: "sidebar-detail-blue",
    name: "Teal Professional",
    description: "Sidebar con tonos turquesa profundos",
    longDescription:
      "Variante del sidebar con tonos Teal/Turquesa. Profesional pero más moderno que el azul clásico. Para salud o tecnología.",
    thumbnail: "https://images.unsplash.com/photo-1498049794561-7780e7231661?w=600&h=400&fit=crop",
    previewImages: [],
    layout: "magazine",
    style: "modern",
    category: "standard",
    isPremium: false,
    bestFor: ["salud", "farmacia", "servicios"],
    idealProductCount: { min: 8, max: 50 },
    features: ["Sidebar lateral", "Especificaciones"],
    config: {
      columnsDesktop: 4,
      columnsMobile: 2,
      gap: "normal",
      cardStyle: "outlined",
      cardRadius: "md",
      imageRatio: "square",
      hoverEffect: "lift",
      clickAction: "sidebar",
      hasSearch: true,
      hasFilters: true,
      hasCart: true,
      hasFavorites: true,
      hasShareButtons: true,
      hasZoom: true,
      entranceAnimation: "fade",
      transitionSpeed: "fast",
      showLogo: true,
      showWatermark: false,
    },
    colorScheme: {
      primary: "#0f766e", // Teal-700
      secondary: "#2dd4bf",
      accent: "#0d9488",
      background: "#f0fdfa",
      cardBackground: "#ffffff",
      text: "#134e4a",
      textMuted: "#5eead4",
      border: "#ccfbf1",
    },
    popularity: 82,
    tags: ["teal", "profesional", "salud"],
  },

  {
    id: "instagram-feed",
    name: "Social Feed",
    description: "Grid cuadrado estilo Instagram",
    longDescription: "Grid perfecto de imágenes cuadradas con gradientes sociales. Familiar y moderno.",
    thumbnail: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=600&h=400&fit=crop",
    previewImages: [],
    layout: "modern-grid",
    style: "modern",
    category: "standard",
    isPremium: false,
    bestFor: ["moda", "cosmeticos", "influencers"],
    idealProductCount: { min: 9, max: 60 },
    features: ["Grid cuadrado", "Estilo app"],
    config: {
      columnsDesktop: 3,
      columnsMobile: 3, // 3 columnas en movil como insta
      gap: "tight",
      cardStyle: "flat",
      cardRadius: "none",
      imageRatio: "square",
      hoverEffect: "zoom",
      clickAction: "modal",
      hasSearch: true,
      hasFilters: false,
      hasCart: true,
      hasFavorites: true,
      hasShareButtons: true,
      hasZoom: true,
      entranceAnimation: "fade",
      transitionSpeed: "fast",
      showLogo: true,
      showWatermark: false,
    },
    colorScheme: {
      primary: "#d946ef", // Fuchsia
      secondary: "#f0abfc",
      accent: "#8b5cf6",
      background: "#faf5ff",
      cardBackground: "#ffffff",
      text: "#1f2937",
      textMuted: "#6b7280",
      border: "#f5d0fe",
      gradient: {
        from: "#f0abfc",
        to: "#8b5cf6",
        direction: "to-r",
      },
    },
    popularity: 93,
    tags: ["instagram", "social", "gradiente"],
  },

  {
    id: "polaroid-vintage",
    name: "Vintage Sepia",
    description: "Estilo polaroid nostálgico",
    longDescription:
      "Cards estilo foto polaroid con rotaciones aleatorias y tonos sepia/café. Para artesanías o recuerdos.",
    thumbnail: "https://images.unsplash.com/photo-1516476892398-f666b0e9d976?w=600&h=400&fit=crop",
    previewImages: [],
    layout: "masonry",
    style: "playful",
    category: "standard",
    isPremium: false,
    bestFor: ["artesania", "recuerdos"],
    idealProductCount: { min: 6, max: 36 },
    features: ["Rotación aleatoria", "Estilo papel"],
    config: {
      columnsDesktop: 3,
      columnsMobile: 1,
      gap: "loose",
      cardStyle: "elevated",
      cardRadius: "sm",
      imageRatio: "square",
      hoverEffect: "tilt",
      clickAction: "modal",
      hasSearch: true,
      hasFilters: true,
      hasCart: true,
      hasFavorites: true,
      hasShareButtons: true,
      hasZoom: true,
      entranceAnimation: "scale",
      transitionSpeed: "normal",
      showLogo: true,
      showWatermark: false,
    },
    colorScheme: {
      primary: "#78350f", // Amber-900
      secondary: "#d97706",
      accent: "#b45309",
      background: "#fffbeb", // Amber-50
      cardBackground: "#ffffff",
      text: "#451a03",
      textMuted: "#92400e",
      border: "#fde68a",
    },
    popularity: 73,
    tags: ["vintage", "sepia", "artesanal"],
  },

  {
    id: "carousel-dynamic",
    name: "Red Dynamic",
    description: "Slider interactivo de alto impacto",
    longDescription: "Carousel moderno en tonos rojos intensos. Ideal para promociones, comida rápida o deportes.",
    thumbnail: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&h=400&fit=crop",
    previewImages: [],
    layout: "carousel",
    style: "playful",
    category: "standard",
    isPremium: false,
    bestFor: ["deportes", "comida", "promociones"],
    idealProductCount: { min: 4, max: 24 },
    features: ["Auto-play", "Touch swipe"],
    config: {
      columnsDesktop: 3,
      columnsMobile: 1,
      gap: "normal",
      cardStyle: "elevated",
      cardRadius: "xl",
      imageRatio: "square",
      hoverEffect: "lift",
      clickAction: "modal",
      hasSearch: false,
      hasFilters: false,
      hasCart: true,
      hasFavorites: false,
      hasShareButtons: true,
      hasZoom: true,
      entranceAnimation: "fade",
      transitionSpeed: "normal",
      showLogo: true,
      showWatermark: false,
    },
    colorScheme: {
      primary: "#dc2626", // Red-600
      secondary: "#ef4444",
      accent: "#f87171",
      background: "#fef2f2",
      cardBackground: "#ffffff",
      text: "#1f2937",
      textMuted: "#6b7280",
      border: "#fecaca",
    },
    popularity: 72,
    tags: ["rojo", "dinámico", "carousel"],
  },

  {
    id: "architect-studio",
    name: "Estudio Arquitecto",
    description: "Líneas finas, Blanco y Negro",
    longDescription: "Inspirado en planos arquitectónicos. Bordes negros finos, sin sombras. Brutalista y limpio.",
    thumbnail: "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=600&h=400&fit=crop",
    previewImages: [],
    layout: "modern-grid",
    style: "minimal",
    category: "standard",
    isPremium: false,
    bestFor: ["muebles", "arquitectura", "arte"],
    idealProductCount: { min: 6, max: 50 },
    features: ["Estilo Wireframe", "Bordes definidos"],
    config: {
      columnsDesktop: 3,
      columnsMobile: 1,
      gap: "normal",
      cardStyle: "outlined",
      cardRadius: "none",
      imageRatio: "square",
      hoverEffect: "none",
      clickAction: "modal",
      hasSearch: true,
      hasFilters: true,
      hasCart: true,
      hasFavorites: false,
      hasShareButtons: true,
      hasZoom: true,
      entranceAnimation: "none",
      transitionSpeed: "fast",
      showLogo: true,
      showWatermark: false,
    },
    colorScheme: {
      primary: "#000000",
      secondary: "#404040",
      accent: "#000000",
      background: "#ffffff",
      cardBackground: "#ffffff",
      text: "#000000",
      textMuted: "#525252",
      border: "#000000",
    },
    popularity: 80,
    tags: ["b&w", "wireframe", "técnico"],
  },

  {
    id: "boutique-line-art",
    name: "Nude Boutique",
    description: "Delicado y femenino en tonos tierra",
    longDescription: "Elegancia minimalista en tonos beige y taupe. Ideal para skincare, lencería o ropa.",
    thumbnail: "https://images.unsplash.com/photo-1445205170230-053b83016050?w=600&h=400&fit=crop",
    previewImages: [],
    layout: "masonry",
    style: "elegant",
    category: "standard",
    isPremium: false,
    bestFor: ["moda", "skincare", "lenceria"],
    idealProductCount: { min: 10, max: 60 },
    features: ["Bordes finos", "Paleta nude"],
    config: {
      columnsDesktop: 4,
      columnsMobile: 2,
      gap: "loose",
      cardStyle: "outlined",
      cardRadius: "sm",
      imageRatio: "portrait",
      hoverEffect: "lift",
      clickAction: "modal",
      hasSearch: true,
      hasFilters: true,
      hasCart: true,
      hasFavorites: true,
      hasShareButtons: true,
      hasZoom: true,
      entranceAnimation: "fade",
      transitionSpeed: "slow",
      showLogo: true,
      showWatermark: false,
    },
    colorScheme: {
      primary: "#a8a29e", // Stone-400
      secondary: "#d6d3d1",
      accent: "#78716c",
      background: "#fafaf9", // Stone-50
      cardBackground: "#ffffff",
      text: "#44403c",
      textMuted: "#a8a29e",
      border: "#e7e5e4",
    },
    popularity: 87,
    tags: ["nude", "boutique", "suave"],
  },

  {
    id: "gallery-frame",
    name: "Museum Grey",
    description: "Marco ancho tipo galería de arte",
    longDescription: "Fondo gris museo y marcos blancos anchos. Resalta la fotografía artística.",
    thumbnail: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=600&h=400&fit=crop",
    previewImages: [],
    layout: "modern-grid",
    style: "minimal",
    category: "standard",
    isPremium: false, // Lo cambié a standard para dar más valor al plan medio
    bestFor: ["arte", "fotografia"],
    idealProductCount: { min: 1, max: 30 },
    features: ["Efecto paspartú", "Sombra profunda"],
    config: {
      columnsDesktop: 3,
      columnsMobile: 1,
      gap: "loose",
      cardStyle: "flat",
      cardRadius: "none",
      imageRatio: "square",
      hoverEffect: "glow",
      clickAction: "modal",
      hasSearch: true,
      hasFilters: false,
      hasCart: true,
      hasFavorites: true,
      hasShareButtons: true,
      hasZoom: true,
      entranceAnimation: "scale",
      transitionSpeed: "normal",
      showLogo: true,
      showWatermark: false,
    },
    colorScheme: {
      primary: "#262626",
      secondary: "#525252",
      accent: "#000000",
      background: "#e5e5e5", // Gris más oscuro
      cardBackground: "#ffffff", // Marco blanco
      text: "#171717",
      textMuted: "#737373",
      border: "transparent",
    },
    popularity: 78,
    tags: ["gris", "arte", "marco"],
  },

  // ============================================
  // CATEGORÍA: SEASONAL / PREMIUM
  // ============================================

  {
    id: "masonry-fashion-dark-premium",
    name: "Midnight Luxury",
    description: "Negro profundo y Dorado",
    longDescription: "Modo oscuro real con detalles en oro. Lujo absoluto para marcas premium.",
    thumbnail: "https://images.unsplash.com/photo-1483985988355-763728e1935b?w=600&h=400&fit=crop",
    previewImages: [],
    layout: "masonry",
    style: "luxury",
    category: "seasonal",
    isPremium: true,
    bestFor: ["joyeria", "vip"],
    idealProductCount: { min: 6, max: 40 },
    features: ["Modo oscuro", "Detalles dorados", "Glassmorphism"],
    config: {
      columnsDesktop: 3,
      columnsMobile: 1,
      gap: "loose",
      cardStyle: "glass",
      cardRadius: "xl",
      imageRatio: "auto",
      hoverEffect: "glow",
      clickAction: "modal",
      hasSearch: true,
      hasFilters: true,
      hasCart: true,
      hasFavorites: true,
      hasShareButtons: true,
      hasZoom: true,
      entranceAnimation: "fade",
      transitionSpeed: "slow",
      showLogo: true,
      showWatermark: false,
    },
    colorScheme: {
      primary: "#fbbf24", // Dorado
      secondary: "#525252",
      accent: "#f59e0b",
      background: "#09090b", // Negro
      cardBackground: "rgba(255, 255, 255, 0.03)",
      text: "#f8fafc",
      textMuted: "#a3a3a3",
      border: "rgba(251, 191, 36, 0.2)",
      gradient: { from: "#18181b", to: "#000000", direction: "to-b" },
    },
    popularity: 98,
    isNew: true,
    tags: ["lujo", "oscuro", "gold"],
  },

  {
    id: "bento-modern-pro",
    name: "Deep Violet Tech",
    description: "Estilo Cyberpunk/Tech moderno",
    longDescription: "Gradientes violetas y azules profundos. Layout Bento estructurado.",
    thumbnail: "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?w=600&h=400&fit=crop",
    previewImages: [],
    layout: "modern-grid",
    style: "modern",
    category: "seasonal",
    isPremium: true,
    bestFor: ["gaming", "tech"],
    idealProductCount: { min: 8, max: 32 },
    features: ["Gradientes modernos", "Layout Bento"],
    config: {
      columnsDesktop: 4,
      columnsMobile: 2,
      gap: "normal",
      cardStyle: "flat",
      cardRadius: "2xl",
      imageRatio: "square",
      hoverEffect: "scale",
      clickAction: "modal",
      hasSearch: true,
      hasFilters: true,
      hasCart: true,
      hasFavorites: true,
      hasShareButtons: true,
      hasZoom: true,
      entranceAnimation: "scale",
      transitionSpeed: "fast",
      showLogo: true,
      showWatermark: false,
    },
    colorScheme: {
      primary: "#8b5cf6", // Violeta
      secondary: "#c4b5fd",
      accent: "#3b82f6",
      background: "#2e1065", // Violeta oscuro
      cardBackground: "#ffffff",
      text: "#ffffff",
      textMuted: "#ddd6fe",
      border: "transparent",
      gradient: { from: "#2e1065", to: "#4c1d95", direction: "to-br" },
    },
    popularity: 92,
    isNew: true,
    tags: ["violeta", "tech", "bento"],
  },

  {
    id: "sidebar-detail-luxury",
    name: "Royal Navy & Gold",
    description: "Sidebar premium en azul marino profundo",
    longDescription: "Layout sidebar con tema azul marino y oro. Muy corporativo y elegante.",
    thumbnail: "https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=600&h=400&fit=crop",
    previewImages: [],
    layout: "magazine",
    style: "luxury",
    category: "seasonal",
    isPremium: true,
    bestFor: ["relojes", "trajes", "corporativo"],
    idealProductCount: { min: 8, max: 50 },
    features: ["Tema oscuro elegante", "Detalles dorados"],
    config: {
      columnsDesktop: 4,
      columnsMobile: 2,
      gap: "normal",
      cardStyle: "glass",
      cardRadius: "xl",
      imageRatio: "square",
      hoverEffect: "glow",
      clickAction: "sidebar",
      hasSearch: true,
      hasFilters: true,
      hasCart: true,
      hasFavorites: true,
      hasShareButtons: true,
      hasZoom: true,
      entranceAnimation: "scale",
      transitionSpeed: "slow",
      showLogo: true,
      showWatermark: false,
    },
    colorScheme: {
      primary: "#fbbf24",
      secondary: "#f59e0b",
      accent: "#fde047",
      background: "#172554", // Blue-950
      cardBackground: "rgba(255, 255, 255, 0.05)",
      text: "#f8fafc",
      textMuted: "#94a3b8",
      border: "rgba(251, 191, 36, 0.2)",
      gradient: { from: "#1e3a8a", to: "#172554", direction: "to-b" },
    },
    popularity: 79,
    isNew: true,
    tags: ["navy", "gold", "luxury"],
  },

  {
    id: "grid-compact-pro",
    name: "Slate Industrial",
    description: "Gris azulado serio y denso",
    longDescription: "Para catálogos industriales con muchos productos. Alta densidad de información.",
    thumbnail: "https://images.unsplash.com/photo-1445205170230-053b83016050?w=600&h=400&fit=crop",
    previewImages: [],
    layout: "modern-grid",
    style: "minimal",
    category: "seasonal",
    isPremium: true,
    bestFor: ["ferreteria", "mayoreo"],
    idealProductCount: { min: 50, max: 500 },
    features: ["Alta densidad", "Colores sobrios"],
    config: {
      columnsDesktop: 5,
      columnsMobile: 2,
      gap: "tight",
      cardStyle: "outlined",
      cardRadius: "sm",
      imageRatio: "square",
      hoverEffect: "lift",
      clickAction: "expand",
      hasSearch: true,
      hasFilters: true,
      hasCart: true,
      hasFavorites: true,
      hasShareButtons: false,
      hasZoom: true,
      entranceAnimation: "none",
      transitionSpeed: "fast",
      showLogo: true,
      showWatermark: false,
    },
    colorScheme: {
      primary: "#334155", // Slate-700
      secondary: "#94a3b8",
      accent: "#475569",
      background: "#f1f5f9",
      cardBackground: "#ffffff",
      text: "#0f172a",
      textMuted: "#64748b",
      border: "#cbd5e1",
    },
    popularity: 76,
    tags: ["gris", "industrial", "compacto"],
  },

  {
    id: "magazine-editorial-pro",
    name: "Vogue Red",
    description: "Alto contraste editorial Rojo/Negro",
    longDescription: "Layout asimétrico inspirado en revistas de moda. Tipografía impactante.",
    thumbnail: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=600&h=400&fit=crop",
    previewImages: [],
    layout: "magazine",
    style: "bold",
    category: "seasonal",
    isPremium: true,
    bestFor: ["moda", "editorial"],
    idealProductCount: { min: 6, max: 30 },
    features: ["Tipografía grande", "Imágenes full-bleed"],
    config: {
      columnsDesktop: 3,
      columnsMobile: 1,
      gap: "loose",
      cardStyle: "flat",
      cardRadius: "none",
      imageRatio: "portrait",
      hoverEffect: "zoom",
      clickAction: "modal",
      hasSearch: false,
      hasFilters: false,
      hasCart: true,
      hasFavorites: true,
      hasShareButtons: true,
      hasZoom: true,
      entranceAnimation: "slide",
      transitionSpeed: "slow",
      showLogo: true,
      showWatermark: false,
      customFonts: ["Playfair Display", "Montserrat"],
    },
    colorScheme: {
      primary: "#991b1b", // Red-800
      secondary: "#dc2626",
      accent: "#000000",
      background: "#ffffff",
      cardBackground: "#f8fafc",
      text: "#0f172a",
      textMuted: "#64748b",
      border: "#e2e8f0",
    },
    popularity: 81,
    isNew: true,
    tags: ["rojo", "editorial", "bold"],
  },

  {
    id: "netflix-carousel-pro",
    name: "Cinema Dark",
    description: "Carousels horizontales estilo streaming",
    longDescription: "Fondo oscuro con carousels horizontales. Perfecto para catálogos visuales grandes.",
    thumbnail: "https://images.unsplash.com/photo-1522869635100-9f4c5e86aa37?w=600&h=400&fit=crop",
    previewImages: [],
    layout: "horizontal-scroll",
    style: "modern",
    category: "seasonal",
    isPremium: true,
    bestFor: ["peliculas", "juegos", "series"],
    idealProductCount: { min: 20, max: 100 },
    features: ["Carousels horizontales", "Scroll fluido"],
    config: {
      columnsDesktop: 5,
      columnsMobile: 2,
      gap: "normal",
      cardStyle: "elevated",
      cardRadius: "md",
      imageRatio: "landscape",
      hoverEffect: "zoom",
      clickAction: "modal",
      hasSearch: true,
      hasFilters: true,
      hasCart: true,
      hasFavorites: true,
      hasShareButtons: true,
      hasZoom: true,
      entranceAnimation: "slide",
      transitionSpeed: "fast",
      showLogo: true,
      showWatermark: false,
    },
    colorScheme: {
      primary: "#ef4444", // Red-500
      secondary: "#b91c1c",
      accent: "#ffffff",
      background: "#141414", // Netflix Black
      cardBackground: "#262626",
      text: "#f8fafc",
      textMuted: "#a3a3a3",
      border: "#404040",
    },
    popularity: 89,
    isNew: true,
    tags: ["oscuro", "netflix", "carousel"],
  },

  {
    id: "showcase-fullscreen-pro",
    name: "Showcase Gold",
    description: "Presentación fullscreen inmersiva",
    longDescription: "Cada producto ocupa toda la pantalla. Transiciones cinematográficas.",
    thumbnail: "https://images.unsplash.com/photo-1618005198920-f0cb6201c115?w=600&h=400&fit=crop",
    previewImages: [],
    layout: "showcase",
    style: "luxury",
    category: "seasonal",
    isPremium: true,
    bestFor: ["autos", "propiedades", "arte"],
    idealProductCount: { min: 5, max: 20 },
    features: ["Fullscreen", "Transiciones"],
    config: {
      columnsDesktop: 2,
      columnsMobile: 2,
      gap: "normal",
      cardStyle: "flat",
      cardRadius: "none",
      imageRatio: "landscape",
      hoverEffect: "tilt",
      clickAction: "modal",
      hasSearch: false,
      hasFilters: false,
      hasCart: true,
      hasFavorites: true,
      hasShareButtons: true,
      hasZoom: true,
      entranceAnimation: "scale",
      transitionSpeed: "slow",
      showLogo: true,
      showWatermark: false,
    },
    colorScheme: {
      primary: "#d4af37", // Metallic Gold
      secondary: "#fbbf24",
      accent: "#ffffff",
      background: "#1a1a1a",
      cardBackground: "#2a2a2a",
      text: "#ffffff",
      textMuted: "#d4d4d4",
      border: "#d4af37",
      gradient: { from: "#1a1a1a", to: "#000000", direction: "to-b" },
    },
    popularity: 75,
    isNew: true,
    tags: ["fullscreen", "gold", "showcase"],
  },

  // ============================================
  // TEMPORADA: FIESTAS
  // ============================================

  {
    id: "christmas-classic",
    name: "Navidad Clásica",
    description: "Festivo rojo y verde",
    longDescription: "El espíritu navideño. Bordes dorados, fondo rojo cálido y detalles festivos.",
    thumbnail: "https://images.unsplash.com/photo-1543589077-47d81606c1bf?w=600&h=400&fit=crop",
    previewImages: [],
    layout: "modern-grid",
    style: "playful",
    category: "seasonal",
    isPremium: false,
    bestFor: ["regalos", "navidad"],
    idealProductCount: { min: 8, max: 50 },
    features: ["Paleta navideña", "Textura sutil"],
    config: {
      columnsDesktop: 3,
      columnsMobile: 2,
      gap: "loose",
      cardStyle: "elevated",
      cardRadius: "xl",
      imageRatio: "square",
      hoverEffect: "bounce",
      clickAction: "modal",
      hasSearch: true,
      hasFilters: true,
      hasCart: true,
      hasFavorites: true,
      hasShareButtons: true,
      hasZoom: true,
      entranceAnimation: "slide",
      transitionSpeed: "normal",
      showLogo: true,
      showWatermark: false,
    },
    colorScheme: {
      primary: "#dc2626", // Rojo
      secondary: "#166534", // Verde
      accent: "#f59e0b", // Dorado
      background: "#fef2f2",
      cardBackground: "#ffffff",
      text: "#7f1d1d",
      textMuted: "#991b1b",
      border: "#fca5a5",
    },
    popularity: 99,
    tags: ["navidad", "rojo", "fiestas"],
  },

  {
    id: "winter-wonderland",
    name: "Frozen Blue",
    description: "Invierno azul hielo y plata",
    longDescription: "Diseño invernal con tonos azules fríos y efecto cristal.",
    thumbnail: "https://images.unsplash.com/photo-1482331318722-b87273d42e4e?w=600&h=400&fit=crop",
    previewImages: [],
    layout: "masonry",
    style: "elegant",
    category: "seasonal",
    isPremium: true,
    bestFor: ["invierno", "joyeria plata"],
    idealProductCount: { min: 6, max: 40 },
    features: ["Estilo Frozen", "Glassmorphism"],
    config: {
      columnsDesktop: 3,
      columnsMobile: 1,
      gap: "normal",
      cardStyle: "glass",
      cardRadius: "lg",
      imageRatio: "auto",
      hoverEffect: "glow",
      clickAction: "modal",
      hasSearch: true,
      hasFilters: true,
      hasCart: true,
      hasFavorites: true,
      hasShareButtons: true,
      hasZoom: true,
      entranceAnimation: "fade",
      transitionSpeed: "slow",
      showLogo: true,
      showWatermark: false,
    },
    colorScheme: {
      primary: "#0ea5e9", // Sky-500
      secondary: "#64748b",
      accent: "#38bdf8",
      background: "#f0f9ff",
      cardBackground: "rgba(255, 255, 255, 0.8)",
      text: "#0c4a6e",
      textMuted: "#64748b",
      border: "#bae6fd",
    },
    popularity: 88,
    tags: ["invierno", "hielo", "azul"],
  },

  {
    id: "new-year-gala",
    name: "Gala Night",
    description: "Elegancia para Año Nuevo",
    longDescription: "Negro y champagne. Perfecto para eventos de fin de año y licores.",
    thumbnail: "https://images.unsplash.com/photo-1467810563316-b5476525c0f9?w=600&h=400&fit=crop",
    previewImages: [],
    layout: "showcase",
    style: "luxury",
    category: "seasonal",
    isPremium: true,
    bestFor: ["fiesta", "licores"],
    idealProductCount: { min: 4, max: 20 },
    features: ["Negro y Champagne", "Showcase"],
    config: {
      columnsDesktop: 2,
      columnsMobile: 1,
      gap: "loose",
      cardStyle: "outlined",
      cardRadius: "none",
      imageRatio: "portrait",
      hoverEffect: "scale",
      clickAction: "modal",
      hasSearch: false,
      hasFilters: false,
      hasCart: true,
      hasFavorites: false,
      hasShareButtons: true,
      hasZoom: true,
      entranceAnimation: "slide",
      transitionSpeed: "slow",
      showLogo: true,
      showWatermark: false,
    },
    colorScheme: {
      primary: "#fcd34d", // Champagne Gold
      secondary: "#d4d4d8",
      accent: "#f59e0b",
      background: "#000000",
      cardBackground: "#18181b",
      text: "#fef3c7",
      textMuted: "#a1a1aa",
      border: "#fcd34d",
    },
    popularity: 85,
    tags: ["gala", "año nuevo", "champagne"],
  },

  // ============================================
  // NUEVOS: BRAND-FIRST (Para "Tu Marca")
  // ============================================

  {
    id: "brand-minimal-clean",
    name: "Tu Marca: Minimalista",
    description: "Diseño limpio adaptable a tu color",
    longDescription: "Fondo blanco puro, bordes sutiles en tu color primario. Ideal para que tu marca destaque.",
    thumbnail: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=600&h=400&fit=crop",
    previewImages: [],
    layout: "modern-grid",
    style: "minimal",
    category: "standard",
    isPremium: false,
    bestFor: ["marca", "corporativo"],
    idealProductCount: { min: 10, max: 100 },
    features: ["Adaptable", "Limpio"],
    config: {
      columnsDesktop: 3,
      columnsMobile: 1,
      gap: "normal",
      cardStyle: "outlined",
      cardRadius: "md",
      imageRatio: "square",
      hoverEffect: "lift",
      clickAction: "modal",
      hasSearch: true,
      hasFilters: true,
      hasCart: true,
      hasFavorites: false,
      hasShareButtons: true,
      hasZoom: true,
      entranceAnimation: "fade",
      transitionSpeed: "normal",
      showLogo: true,
      showWatermark: false,
    },
    colorScheme: {
      primary: "#000000", // Placeholder, se sobrescribe
      secondary: "#333333",
      accent: "#666666",
      background: "#ffffff",
      cardBackground: "#ffffff",
      text: "#09090b",
      textMuted: "#71717a",
      border: "#e4e4e7",
    },
    popularity: 96,
    tags: ["adaptable", "marca"],
  },

  {
    id: "brand-modern-glass",
    name: "Tu Marca: Cristal",
    description: "Estilo moderno con gradientes de tu marca",
    longDescription: "Usa tu color para crear un fondo degradado suave con tarjetas flotantes.",
    thumbnail: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&h=400&fit=crop",
    previewImages: [],
    layout: "masonry",
    style: "modern",
    category: "standard",
    isPremium: true,
    bestFor: ["app", "tech"],
    idealProductCount: { min: 6, max: 50 },
    features: ["Gradiente de marca", "Glass effect"],
    config: {
      columnsDesktop: 3,
      columnsMobile: 2,
      gap: "loose",
      cardStyle: "elevated",
      cardRadius: "xl",
      imageRatio: "auto",
      hoverEffect: "zoom",
      clickAction: "modal",
      hasSearch: true,
      hasFilters: true,
      hasCart: true,
      hasFavorites: true,
      hasShareButtons: true,
      hasZoom: true,
      entranceAnimation: "stagger",
      transitionSpeed: "normal",
      showLogo: true,
      showWatermark: false,
    },
    colorScheme: {
      primary: "#2563eb",
      secondary: "#1e40af",
      accent: "#60a5fa",
      background: "#f8fafc",
      cardBackground: "#ffffff",
      text: "#0f172a",
      textMuted: "#64748b",
      border: "transparent",
    },
    popularity: 92,
    tags: ["adaptable", "moderno"],
  },

  {
    id: "brand-bold-impact",
    name: "Tu Marca: Impacto",
    description: "Encabezados sólidos con tu color",
    longDescription: "Usa tu color con fuerza en los encabezados y botones grandes.",
    thumbnail: "https://images.unsplash.com/photo-1550684848-fac1c5b4e853?w=600&h=400&fit=crop",
    previewImages: [],
    layout: "modern-grid",
    style: "bold",
    category: "seasonal",
    isPremium: true,
    bestFor: ["retail", "impacto"],
    idealProductCount: { min: 12, max: 80 },
    features: ["Header sólido", "Alto impacto"],
    config: {
      columnsDesktop: 4,
      columnsMobile: 2,
      gap: "tight",
      cardStyle: "flat",
      cardRadius: "sm",
      imageRatio: "square",
      hoverEffect: "glow",
      clickAction: "modal",
      hasSearch: true,
      hasFilters: true,
      hasCart: true,
      hasFavorites: false,
      hasShareButtons: true,
      hasZoom: true,
      entranceAnimation: "slide",
      transitionSpeed: "fast",
      showLogo: true,
      showWatermark: false,
    },
    colorScheme: {
      primary: "#000000",
      secondary: "#333333",
      accent: "#ffffff",
      background: "#ffffff",
      cardBackground: "#f8f9fa",
      text: "#212529",
      textMuted: "#6c757d",
      border: "transparent",
    },
    popularity: 89,
    tags: ["adaptable", "fuerte"],
  },
];
